### PR TITLE
Specifically for Android

### PR DESCRIPTION
**Pull request by agentps2066**
I have seen many issues due to height limits

### CODE REVIEW

**Comment by arnaud512** [comment]
hey @agentps2066 ! can you provide a screen before and after? I don't have an android phone to test!

**Comment by agentps2066** [comment]
Sure can provide the raw link to run

**Comment by agentps2066** [comment]
Actually i am a newbie to git hub but i have previously worked with Android, you see 400px height most of the times gets obstructed by the rounded corners and waterdrop notches which is quite common in phones these days

**Comment by arnaud512** [comment]
So why did you increase?

**Pull request closed without merging**
