### PR TITLE
Add all countryes spotify avaibles

### PR DESCRIPTION
**Pull request by lucianodlf**
Hello, I had started to work adding the rest of the cities, then I saw the issue closed. Anyway I send you the finished work. As I saw in # 4 check the information in https://support.spotify.com/us/article/full-list-of-territories-where-spotify-is-available/ and add the codes according to https://www.iso.org/obp/ui/#search.
I hope my work is useful and if not, it was a good experience 😃 
I was thinking of ordering them alphabetically ...

It is one of my first contributions and I apologize if something is not done correctly, we all have to learn.
an Argentine hug!

### CODE REVIEW

**Comment by arnaud512** [comment]
Hey! Yeah, I closed the issue, bcs, all people were taking this issue to add just a few countries!

But thank's for your contribution :)
I'll check the list tomorrow! 

And if everything is ok, I'll merge your work! :)

But yeah, an ordered list would be better :D 

Thanks! 
A 2-meter hug from Canada :D

**Comment by lucianodlf** [comment]
Thank you very much! If you think it's okay, I accept your comments and order the list tomorrow so that it is neater.

good night (from these latitudes)

**Comment by lucianodlf** [comment]
@arnaud512 i sorted list of countryes and delete duplicates.

hug

**Comment by arnaud512** [comment]
merged! Thanks a lot for this 👍  :)

**Pull request merged**
